// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwzKRU4bUZzBDmH83tnRtt8PfBMMLOg0Q',
    appId: '1:362336765894:web:ad5a78d69b8989dbe114c7',
    messagingSenderId: '362336765894',
    projectId: 'dailyquestion-29840',
    authDomain: 'dailyquestion-29840.firebaseapp.com',
    storageBucket: 'dailyquestion-29840.firebasestorage.app',
    measurementId: 'G-MS633L9T5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfs0F5KJya5-FSPwqk-JRq7jgkPk98wCo',
    appId: '1:362336765894:android:4c29e5239c5fc13ae114c7',
    messagingSenderId: '362336765894',
    projectId: 'dailyquestion-29840',
    storageBucket: 'dailyquestion-29840.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUCqEYzn5E59eWyLF899UdR3250PWJZ8',
    appId: '1:362336765894:ios:b3504b7e3144ff45e114c7',
    messagingSenderId: '362336765894',
    projectId: 'dailyquestion-29840',
    storageBucket: 'dailyquestion-29840.firebasestorage.app',
    androidClientId: '362336765894-b6ruclpp624oa3q7nhkvut3u81giich3.apps.googleusercontent.com',
    iosClientId: '362336765894-ieckmi58806t8gvbmeq1l2343iakfvk8.apps.googleusercontent.com',
    iosBundleId: 'com.hyesun.dailyquestion',
  );
}
